export const addressTableUtil = [
  {
    name: "Test",
    token: "ETH",
    network: "ERC-20",
    walletaddress: "Tx1234abcdegfu",
    whiteliststatus: "Not Approved",
    declarationform: "Signed",
    status: "Active",
  },
  {
    name: "Test",
    token: "ETH",
    network: "ERC-20",
    walletaddress: "Tx1234abcdegfu",
    whiteliststatus: "Not Approved",
    declarationform: "Signed",
    status: "Active",
  },
  {
    name: "Test",
    token: "ETH",
    network: "ERC-20",
    walletaddress: "Tx1234abcdegfu",
    whiteliststatus: "Not Approved",
    declarationform: "Signed",
    status: "Active",
  },
  {
    name: "Test",
    token: "ETH",
    network: "ERC-20",
    walletaddress: "Tx1234abcdegfu",
    whiteliststatus: "Not Approved",
    declarationform: "Signed",
    status: "Active",
  },
  {
    name: "Test",
    token: "ETH",
    network: "ERC-20",
    walletaddress: "Tx1234abcdegfu",
    whiteliststatus: "Not Approved",
    declarationform: "Signed",
    status: "Active",
  },
  {
    name: "Test",
    token: "ETH",
    network: "ERC-20",
    walletaddress: "Tx1234abcdegfu",
    whiteliststatus: "Not Approved",
    declarationform: "Signed",
    status: "Active",
  },
  {
    name: "Test",
    token: "ETH",
    network: "ERC-20",
    walletaddress: "Tx1234abcdegfu",
    whiteliststatus: "Not Approved",
    declarationform: "Signed",
    status: "Active",
  },
  {
    name: "Test",
    token: "ETH",
    network: "ERC-20",
    walletaddress: "Tx1234abcdegfu",
    whiteliststatus: "Not Approved",
    declarationform: "Signed",
    status: "Active",
  },
  {
    name: "Test",
    token: "ETH",
    network: "ERC-20",
    walletaddress: "Tx1234abcdegfu",
    whiteliststatus: "Not Approved",
    declarationform: "Signed",
    status: "Active",
  },
];

export const addressTableUtilFiat = [
  {
    name: "Test",
    currency: "USD",
    bankaccount: "87399456",
    swift: "CHA89979798789",
    bankname: "JP Morgan",
    status: "Active",
  },
  {
    name: "Test",
    currency: "USD",
    bankaccount: "87399456",
    swift: "CHA89979798789",
    bankname: "JP Morgan",
    status: "Active",
  },
  {
    name: "Test",
    currency: "USD",
    bankaccount: "87399456",
    swift: "CHA89979798789",
    bankname: "JP Morgan",
    status: "Active",
  },
  {
    name: "Test",
    currency: "USD",
    bankaccount: "87399456",
    swift: "CHA89979798789",
    bankname: "JP Morgan",
    status: "Active",
  },
  {
    name: "Test",
    currency: "USD",
    bankaccount: "87399456",
    swift: "CHA89979798789",
    bankname: "JP Morgan",
    status: "Active",
  },
  {
    name: "Test",
    currency: "USD",
    bankaccount: "87399456",
    swift: "CHA89979798789",
    bankname: "JP Morgan",
    status: "Active",
  },
  {
    name: "Test",
    currency: "USD",
    bankaccount: "87399456",
    swift: "CHA89979798789",
    bankname: "JP Morgan",
    status: "Active",
  },
  {
    name: "Test",
    currency: "USD",
    bankaccount: "87399456",
    swift: "CHA89979798789",
    bankname: "JP Morgan",
    status: "Active",
  },
  {
    name: "Test",
    currency: "USD",
    bankaccount: "87399456",
    swift: "CHA89979798789",
    bankname: "JP Morgan",
    status: "Active",
  },
];
