export const countries = [
  {
    id: 1,
    country_long_name: "Afghanistan",
    country_short_name3: "AFG",
    country_short_name2: "AF",
    country_phone_code: "93",
  },
  {
    id: 2,
    country_long_name: "Albania",
    country_short_name3: "ALB",
    country_short_name2: "AL",
    country_phone_code: "355",
  },
  {
    id: 3,
    country_long_name: "Algeria",
    country_short_name3: "DZA",
    country_short_name2: "DZ",
    country_phone_code: "213",
  },
  {
    id: 4,
    country_long_name: "American Samoa",
    country_short_name3: "ASM",
    country_short_name2: "AS",
    country_phone_code: "1-684",
  },
  {
    id: 5,
    country_long_name: "Andorra",
    country_short_name3: "AND",
    country_short_name2: "AD",
    country_phone_code: "376",
  },
  {
    id: 6,
    country_long_name: "Angola",
    country_short_name3: "AGO",
    country_short_name2: "AO",
    country_phone_code: "244",
  },
  {
    id: 7,
    country_long_name: "Anguilla",
    country_short_name3: "AIA",
    country_short_name2: "AI",
    country_phone_code: "1-264",
  },
  {
    id: 8,
    country_long_name: "Antarctica",
    country_short_name3: "ATA",
    country_short_name2: "AQ",
    country_phone_code: "672",
  },
  {
    id: 9,
    country_long_name: "Antigua and Barbuda",
    country_short_name3: "ATG",
    country_short_name2: "AG",
    country_phone_code: "1-268",
  },
  {
    id: 10,
    country_long_name: "Argentina",
    country_short_name3: "ARG",
    country_short_name2: "AR",
    country_phone_code: "54",
  },
  {
    id: 11,
    country_long_name: "Armenia",
    country_short_name3: "ARM",
    country_short_name2: "AM",
    country_phone_code: "374",
  },
  {
    id: 12,
    country_long_name: "Aruba",
    country_short_name3: "ABW",
    country_short_name2: "AW",
    country_phone_code: "297",
  },
  {
    id: 13,
    country_long_name: "Australia",
    country_short_name3: "AUS",
    country_short_name2: "AU",
    country_phone_code: "61",
  },
  {
    id: 14,
    country_long_name: "Austria",
    country_short_name3: "AUT",
    country_short_name2: "AT",
    country_phone_code: "43",
  },
  {
    id: 15,
    country_long_name: "Azerbaijan",
    country_short_name3: "AZE",
    country_short_name2: "AZ",
    country_phone_code: "994",
  },
  {
    id: 16,
    country_long_name: "Bahamas",
    country_short_name3: "BHS",
    country_short_name2: "BS",
    country_phone_code: "1-242",
  },
  {
    id: 17,
    country_long_name: "Bahrain",
    country_short_name3: "BHR",
    country_short_name2: "BH",
    country_phone_code: "973",
  },
  {
    id: 18,
    country_long_name: "Bangladesh",
    country_short_name3: "BGD",
    country_short_name2: "BD",
    country_phone_code: "880",
  },
  {
    id: 19,
    country_long_name: "Barbados",
    country_short_name3: "BRB",
    country_short_name2: "BB",
    country_phone_code: "1-246",
  },
  {
    id: 20,
    country_long_name: "Belarus",
    country_short_name3: "BLR",
    country_short_name2: "BY",
    country_phone_code: "375",
  },
  {
    id: 21,
    country_long_name: "Belgium",
    country_short_name3: "BEL",
    country_short_name2: "BE",
    country_phone_code: "32",
  },
  {
    id: 22,
    country_long_name: "Belize",
    country_short_name3: "BLZ",
    country_short_name2: "BZ",
    country_phone_code: "501",
  },
  {
    id: 23,
    country_long_name: "Benin",
    country_short_name3: "BEN",
    country_short_name2: "BJ",
    country_phone_code: "229",
  },
  {
    id: 24,
    country_long_name: "Bermuda",
    country_short_name3: "BMU",
    country_short_name2: "BM",
    country_phone_code: "1-441",
  },
  {
    id: 25,
    country_long_name: "Bhutan",
    country_short_name3: "BTN",
    country_short_name2: "BT",
    country_phone_code: "975",
  },
  {
    id: 26,
    country_long_name: "Bolivia",
    country_short_name3: "BOL",
    country_short_name2: "BO",
    country_phone_code: "591",
  },
  {
    id: 27,
    country_long_name: "Bosnia and Herzegovina",
    country_short_name3: "BIH",
    country_short_name2: "BA",
    country_phone_code: "387",
  },
  {
    id: 28,
    country_long_name: "Botswana",
    country_short_name3: "BWA",
    country_short_name2: "BW",
    country_phone_code: "267",
  },
  {
    id: 29,
    country_long_name: "Brazil",
    country_short_name3: "BRA",
    country_short_name2: "BR",
    country_phone_code: "55",
  },
  {
    id: 30,
    country_long_name: "British Indian Ocean Territory",
    country_short_name3: "IOT",
    country_short_name2: "IO",
    country_phone_code: "246",
  },
  {
    id: 31,
    country_long_name: "British Virgin Islands",
    country_short_name3: "VGB",
    country_short_name2: "VG",
    country_phone_code: "1-284",
  },
  {
    id: 32,
    country_long_name: "Brunei",
    country_short_name3: "BRN",
    country_short_name2: "BN",
    country_phone_code: "673",
  },
  {
    id: 33,
    country_long_name: "Bulgaria",
    country_short_name3: "BGR",
    country_short_name2: "BG",
    country_phone_code: "359",
  },
  {
    id: 34,
    country_long_name: "Burkina Faso",
    country_short_name3: "BFA",
    country_short_name2: "BF",
    country_phone_code: "226",
  },
  {
    id: 35,
    country_long_name: "Burundi",
    country_short_name3: "BDI",
    country_short_name2: "BI",
    country_phone_code: "257",
  },
  {
    id: 36,
    country_long_name: "Cambodia",
    country_short_name3: "KHM",
    country_short_name2: "KH",
    country_phone_code: "855",
  },
  {
    id: 37,
    country_long_name: "Cameroon",
    country_short_name3: "CMR",
    country_short_name2: "CM",
    country_phone_code: "237",
  },
  {
    id: 38,
    country_long_name: "Canada",
    country_short_name3: "CAN",
    country_short_name2: "CA",
    country_phone_code: "1",
  },
  {
    id: 39,
    country_long_name: "Cape Verde",
    country_short_name3: "CPV",
    country_short_name2: "CV",
    country_phone_code: "238",
  },
  {
    id: 40,
    country_long_name: "Cayman Islands",
    country_short_name3: "CYM",
    country_short_name2: "KY",
    country_phone_code: "1-345",
  },
  {
    id: 41,
    country_long_name: "Central African Republic",
    country_short_name3: "CAF",
    country_short_name2: "CF",
    country_phone_code: "236",
  },
  {
    id: 42,
    country_long_name: "Chad",
    country_short_name3: "TCD",
    country_short_name2: "TD",
    country_phone_code: "235",
  },
  {
    id: 43,
    country_long_name: "Chile",
    country_short_name3: "CHL",
    country_short_name2: "CL",
    country_phone_code: "56",
  },
  {
    id: 44,
    country_long_name: "China",
    country_short_name3: "CHN",
    country_short_name2: "CN",
    country_phone_code: "86",
  },
  {
    id: 45,
    country_long_name: "Christmas Island",
    country_short_name3: "CXR",
    country_short_name2: "CX",
    country_phone_code: "61",
  },
  {
    id: 46,
    country_long_name: "Cocos Islands",
    country_short_name3: "CCK",
    country_short_name2: "CC",
    country_phone_code: "61",
  },
  {
    id: 47,
    country_long_name: "Colombia",
    country_short_name3: "COL",
    country_short_name2: "CO",
    country_phone_code: "57",
  },
  {
    id: 48,
    country_long_name: "Comoros",
    country_short_name3: "COM",
    country_short_name2: "KM",
    country_phone_code: "269",
  },
  {
    id: 49,
    country_long_name: "Cook Islands",
    country_short_name3: "COK",
    country_short_name2: "CK",
    country_phone_code: "682",
  },
  {
    id: 50,
    country_long_name: "Costa Rica",
    country_short_name3: "CRI",
    country_short_name2: "CR",
    country_phone_code: "506",
  },
  {
    id: 51,
    country_long_name: "Croatia",
    country_short_name3: "HRV",
    country_short_name2: "HR",
    country_phone_code: "385",
  },
  {
    id: 52,
    country_long_name: "Cuba",
    country_short_name3: "CUB",
    country_short_name2: "CU",
    country_phone_code: "53",
  },
  {
    id: 53,
    country_long_name: "Curacao",
    country_short_name3: "CUW",
    country_short_name2: "CW",
    country_phone_code: "599",
  },
  {
    id: 54,
    country_long_name: "Cyprus",
    country_short_name3: "CYP",
    country_short_name2: "CY",
    country_phone_code: "357",
  },
  {
    id: 55,
    country_long_name: "Czech Republic",
    country_short_name3: "CZE",
    country_short_name2: "CZ",
    country_phone_code: "420",
  },
  {
    id: 56,
    country_long_name: "Democratic Republic of the Congo",
    country_short_name3: "COD",
    country_short_name2: "CD",
    country_phone_code: "243",
  },
  {
    id: 57,
    country_long_name: "Denmark",
    country_short_name3: "DNK",
    country_short_name2: "DK",
    country_phone_code: "45",
  },
  {
    id: 58,
    country_long_name: "Djibouti",
    country_short_name3: "DJI",
    country_short_name2: "DJ",
    country_phone_code: "253",
  },
  {
    id: 59,
    country_long_name: "Dominica",
    country_short_name3: "DMA",
    country_short_name2: "DM",
    country_phone_code: "1-767",
  },
  {
    id: 60,
    country_long_name: "Dominican Republic",
    country_short_name3: " 1-829",
    country_short_name2: " 1-849",
    country_phone_code: "1-809",
  },
  {
    id: 61,
    country_long_name: "East Timor",
    country_short_name3: "TLS",
    country_short_name2: "TL",
    country_phone_code: "670",
  },
  {
    id: 62,
    country_long_name: "Ecuador",
    country_short_name3: "ECU",
    country_short_name2: "EC",
    country_phone_code: "593",
  },
  {
    id: 63,
    country_long_name: "Egypt",
    country_short_name3: "EGY",
    country_short_name2: "EG",
    country_phone_code: "20",
  },
  {
    id: 64,
    country_long_name: "El Salvador",
    country_short_name3: "SLV",
    country_short_name2: "SV",
    country_phone_code: "503",
  },
  {
    id: 65,
    country_long_name: "Equatorial Guinea",
    country_short_name3: "GNQ",
    country_short_name2: "GQ",
    country_phone_code: "240",
  },
  {
    id: 66,
    country_long_name: "Eritrea",
    country_short_name3: "ERI",
    country_short_name2: "ER",
    country_phone_code: "291",
  },
  {
    id: 67,
    country_long_name: "Estonia",
    country_short_name3: "EST",
    country_short_name2: "EE",
    country_phone_code: "372",
  },
  {
    id: 68,
    country_long_name: "Ethiopia",
    country_short_name3: "ETH",
    country_short_name2: "ET",
    country_phone_code: "251",
  },
  {
    id: 69,
    country_long_name: "Falkland Islands",
    country_short_name3: "FLK",
    country_short_name2: "FK",
    country_phone_code: "500",
  },
  {
    id: 70,
    country_long_name: "Faroe Islands",
    country_short_name3: "FRO",
    country_short_name2: "FO",
    country_phone_code: "298",
  },
  {
    id: 71,
    country_long_name: "Fiji",
    country_short_name3: "FJI",
    country_short_name2: "FJ",
    country_phone_code: "679",
  },
  {
    id: 72,
    country_long_name: "Finland",
    country_short_name3: "FIN",
    country_short_name2: "FI",
    country_phone_code: "358",
  },
  {
    id: 73,
    country_long_name: "France",
    country_short_name3: "FRA",
    country_short_name2: "FR",
    country_phone_code: "33",
  },
  {
    id: 74,
    country_long_name: "French Polynesia",
    country_short_name3: "PYF",
    country_short_name2: "PF",
    country_phone_code: "689",
  },
  {
    id: 75,
    country_long_name: "Gabon",
    country_short_name3: "GAB",
    country_short_name2: "GA",
    country_phone_code: "241",
  },
  {
    id: 76,
    country_long_name: "Gambia",
    country_short_name3: "GMB",
    country_short_name2: "GM",
    country_phone_code: "220",
  },
  {
    id: 77,
    country_long_name: "Georgia",
    country_short_name3: "GEO",
    country_short_name2: "GE",
    country_phone_code: "995",
  },
  {
    id: 78,
    country_long_name: "Germany",
    country_short_name3: "DEU",
    country_short_name2: "DE",
    country_phone_code: "49",
  },
  {
    id: 79,
    country_long_name: "Ghana",
    country_short_name3: "GHA",
    country_short_name2: "GH",
    country_phone_code: "233",
  },
  {
    id: 80,
    country_long_name: "Gibraltar",
    country_short_name3: "GIB",
    country_short_name2: "GI",
    country_phone_code: "350",
  },
  {
    id: 81,
    country_long_name: "Greece",
    country_short_name3: "GRC",
    country_short_name2: "GR",
    country_phone_code: "30",
  },
  {
    id: 82,
    country_long_name: "Greenland",
    country_short_name3: "GRL",
    country_short_name2: "GL",
    country_phone_code: "299",
  },
  {
    id: 83,
    country_long_name: "Grenada",
    country_short_name3: "GRD",
    country_short_name2: "GD",
    country_phone_code: "1-473",
  },
  {
    id: 84,
    country_long_name: "Guam",
    country_short_name3: "GUM",
    country_short_name2: "GU",
    country_phone_code: "1-671",
  },
  {
    id: 85,
    country_long_name: "Guatemala",
    country_short_name3: "GTM",
    country_short_name2: "GT",
    country_phone_code: "502",
  },
  {
    id: 86,
    country_long_name: "Guernsey",
    country_short_name3: "GGY",
    country_short_name2: "GG",
    country_phone_code: "44-1481",
  },
  {
    id: 87,
    country_long_name: "Guinea",
    country_short_name3: "GIN",
    country_short_name2: "GN",
    country_phone_code: "224",
  },
  {
    id: 88,
    country_long_name: "Guinea-Bissau",
    country_short_name3: "GNB",
    country_short_name2: "GW",
    country_phone_code: "245",
  },
  {
    id: 89,
    country_long_name: "Guyana",
    country_short_name3: "GUY",
    country_short_name2: "GY",
    country_phone_code: "592",
  },
  {
    id: 90,
    country_long_name: "Haiti",
    country_short_name3: "HTI",
    country_short_name2: "HT",
    country_phone_code: "509",
  },
  {
    id: 91,
    country_long_name: "Honduras",
    country_short_name3: "HND",
    country_short_name2: "HN",
    country_phone_code: "504",
  },
  {
    id: 92,
    country_long_name: "Hong Kong",
    country_short_name3: "HKG",
    country_short_name2: "HK",
    country_phone_code: "852",
  },
  {
    id: 93,
    country_long_name: "Hungary",
    country_short_name3: "HUN",
    country_short_name2: "HU",
    country_phone_code: "36",
  },
  {
    id: 94,
    country_long_name: "Iceland",
    country_short_name3: "ISL",
    country_short_name2: "IS",
    country_phone_code: "354",
  },
  {
    id: 95,
    country_long_name: "India",
    country_short_name3: "IND",
    country_short_name2: "IN",
    country_phone_code: "91",
  },
  {
    id: 96,
    country_long_name: "Indonesia",
    country_short_name3: "IDN",
    country_short_name2: "ID",
    country_phone_code: "62",
  },
  {
    id: 97,
    country_long_name: "Iran",
    country_short_name3: "IRN",
    country_short_name2: "IR",
    country_phone_code: "98",
  },
  {
    id: 98,
    country_long_name: "Iraq",
    country_short_name3: "IRQ",
    country_short_name2: "IQ",
    country_phone_code: "964",
  },
  {
    id: 99,
    country_long_name: "Ireland",
    country_short_name3: "IRL",
    country_short_name2: "IE",
    country_phone_code: "353",
  },
  {
    id: 100,
    country_long_name: "Isle of Man",
    country_short_name3: "IMN",
    country_short_name2: "IM",
    country_phone_code: "44-1624",
  },
  {
    id: 101,
    country_long_name: "Israel",
    country_short_name3: "ISR",
    country_short_name2: "IL",
    country_phone_code: "972",
  },
  {
    id: 102,
    country_long_name: "Italy",
    country_short_name3: "ITA",
    country_short_name2: "IT",
    country_phone_code: "39",
  },
  {
    id: 103,
    country_long_name: "Ivory Coast",
    country_short_name3: "CIV",
    country_short_name2: "CI",
    country_phone_code: "225",
  },
  {
    id: 104,
    country_long_name: "Jamaica",
    country_short_name3: "JAM",
    country_short_name2: "JM",
    country_phone_code: "1-876",
  },
  {
    id: 105,
    country_long_name: "Japan",
    country_short_name3: "JPN",
    country_short_name2: "JP",
    country_phone_code: "81",
  },
  {
    id: 106,
    country_long_name: "Jersey",
    country_short_name3: "JEY",
    country_short_name2: "JE",
    country_phone_code: "44-1534",
  },
  {
    id: 107,
    country_long_name: "Jordan",
    country_short_name3: "JOR",
    country_short_name2: "JO",
    country_phone_code: "962",
  },
  {
    id: 108,
    country_long_name: "Kazakhstan",
    country_short_name3: "KAZ",
    country_short_name2: "KZ",
    country_phone_code: "7",
  },
  {
    id: 109,
    country_long_name: "Kenya",
    country_short_name3: "KEN",
    country_short_name2: "KE",
    country_phone_code: "254",
  },
  {
    id: 110,
    country_long_name: "Kiribati",
    country_short_name3: "KIR",
    country_short_name2: "KI",
    country_phone_code: "686",
  },
  {
    id: 111,
    country_long_name: "Kosovo",
    country_short_name3: "XKX",
    country_short_name2: "XK",
    country_phone_code: "383",
  },
  {
    id: 112,
    country_long_name: "Kuwait",
    country_short_name3: "KWT",
    country_short_name2: "KW",
    country_phone_code: "965",
  },
  {
    id: 113,
    country_long_name: "Kyrgyzstan",
    country_short_name3: "KGZ",
    country_short_name2: "KG",
    country_phone_code: "996",
  },
  {
    id: 114,
    country_long_name: "Laos",
    country_short_name3: "LAO",
    country_short_name2: "LA",
    country_phone_code: "856",
  },
  {
    id: 115,
    country_long_name: "Latvia",
    country_short_name3: "LVA",
    country_short_name2: "LV",
    country_phone_code: "371",
  },
  {
    id: 116,
    country_long_name: "Lebanon",
    country_short_name3: "LBN",
    country_short_name2: "LB",
    country_phone_code: "961",
  },
  {
    id: 117,
    country_long_name: "Lesotho",
    country_short_name3: "LSO",
    country_short_name2: "LS",
    country_phone_code: "266",
  },
  {
    id: 118,
    country_long_name: "Liberia",
    country_short_name3: "LBR",
    country_short_name2: "LR",
    country_phone_code: "231",
  },
  {
    id: 119,
    country_long_name: "Libya",
    country_short_name3: "LBY",
    country_short_name2: "LY",
    country_phone_code: "218",
  },
  {
    id: 120,
    country_long_name: "Liechtenstein",
    country_short_name3: "LIE",
    country_short_name2: "LI",
    country_phone_code: "423",
  },
  {
    id: 121,
    country_long_name: "Lithuania",
    country_short_name3: "LTU",
    country_short_name2: "LT",
    country_phone_code: "370",
  },
  {
    id: 122,
    country_long_name: "Luxembourg",
    country_short_name3: "LUX",
    country_short_name2: "LU",
    country_phone_code: "352",
  },
  {
    id: 123,
    country_long_name: "Macau",
    country_short_name3: "MAC",
    country_short_name2: "MO",
    country_phone_code: "853",
  },
  {
    id: 124,
    country_long_name: "Macedonia",
    country_short_name3: "MKD",
    country_short_name2: "MK",
    country_phone_code: "389",
  },
  {
    id: 125,
    country_long_name: "Madagascar",
    country_short_name3: "MDG",
    country_short_name2: "MG",
    country_phone_code: "261",
  },
  {
    id: 126,
    country_long_name: "Malawi",
    country_short_name3: "MWI",
    country_short_name2: "MW",
    country_phone_code: "265",
  },
  {
    id: 127,
    country_long_name: "Malaysia",
    country_short_name3: "MYS",
    country_short_name2: "MY",
    country_phone_code: "60",
  },
  {
    id: 128,
    country_long_name: "Maldives",
    country_short_name3: "MDV",
    country_short_name2: "MV",
    country_phone_code: "960",
  },
  {
    id: 129,
    country_long_name: "Mali",
    country_short_name3: "MLI",
    country_short_name2: "ML",
    country_phone_code: "223",
  },
  {
    id: 130,
    country_long_name: "Malta",
    country_short_name3: "MLT",
    country_short_name2: "MT",
    country_phone_code: "356",
  },
  {
    id: 131,
    country_long_name: "Marshall Islands",
    country_short_name3: "MHL",
    country_short_name2: "MH",
    country_phone_code: "692",
  },
  {
    id: 132,
    country_long_name: "Mauritania",
    country_short_name3: "MRT",
    country_short_name2: "MR",
    country_phone_code: "222",
  },
  {
    id: 133,
    country_long_name: "Mauritius",
    country_short_name3: "MUS",
    country_short_name2: "MU",
    country_phone_code: "230",
  },
  {
    id: 134,
    country_long_name: "Mayotte",
    country_short_name3: "MYT",
    country_short_name2: "YT",
    country_phone_code: "262",
  },
  {
    id: 135,
    country_long_name: "Mexico",
    country_short_name3: "MEX",
    country_short_name2: "MX",
    country_phone_code: "52",
  },
  {
    id: 136,
    country_long_name: "Micronesia",
    country_short_name3: "FSM",
    country_short_name2: "FM",
    country_phone_code: "691",
  },
  {
    id: 137,
    country_long_name: "Moldova",
    country_short_name3: "MDA",
    country_short_name2: "MD",
    country_phone_code: "373",
  },
  {
    id: 138,
    country_long_name: "Monaco",
    country_short_name3: "MCO",
    country_short_name2: "MC",
    country_phone_code: "377",
  },
  {
    id: 139,
    country_long_name: "Mongolia",
    country_short_name3: "MNG",
    country_short_name2: "MN",
    country_phone_code: "976",
  },
  {
    id: 140,
    country_long_name: "Montenegro",
    country_short_name3: "MNE",
    country_short_name2: "ME",
    country_phone_code: "382",
  },
  {
    id: 141,
    country_long_name: "Montserrat",
    country_short_name3: "MSR",
    country_short_name2: "MS",
    country_phone_code: "1-664",
  },
  {
    id: 142,
    country_long_name: "Morocco",
    country_short_name3: "MAR",
    country_short_name2: "MA",
    country_phone_code: "212",
  },
  {
    id: 143,
    country_long_name: "Mozambique",
    country_short_name3: "MOZ",
    country_short_name2: "MZ",
    country_phone_code: "258",
  },
  {
    id: 144,
    country_long_name: "Myanmar",
    country_short_name3: "MMR",
    country_short_name2: "MM",
    country_phone_code: "95",
  },
  {
    id: 145,
    country_long_name: "Namibia",
    country_short_name3: "NAM",
    country_short_name2: null,
    country_phone_code: "264",
  },
  {
    id: 146,
    country_long_name: "Nauru",
    country_short_name3: "NRU",
    country_short_name2: "NR",
    country_phone_code: "674",
  },
  {
    id: 147,
    country_long_name: "Nepal",
    country_short_name3: "NPL",
    country_short_name2: "NP",
    country_phone_code: "977",
  },
  {
    id: 148,
    country_long_name: "Netherlands",
    country_short_name3: "NLD",
    country_short_name2: "NL",
    country_phone_code: "31",
  },
  {
    id: 149,
    country_long_name: "Netherlands Antilles",
    country_short_name3: "ANT",
    country_short_name2: "AN",
    country_phone_code: "599",
  },
  {
    id: 150,
    country_long_name: "New Caledonia",
    country_short_name3: "NCL",
    country_short_name2: "NC",
    country_phone_code: "687",
  },
  {
    id: 151,
    country_long_name: "New Zealand",
    country_short_name3: "NZL",
    country_short_name2: "NZ",
    country_phone_code: "64",
  },
  {
    id: 152,
    country_long_name: "Nicaragua",
    country_short_name3: "NIC",
    country_short_name2: "NI",
    country_phone_code: "505",
  },
  {
    id: 153,
    country_long_name: "Niger",
    country_short_name3: "NER",
    country_short_name2: "NE",
    country_phone_code: "227",
  },
  {
    id: 154,
    country_long_name: "Nigeria",
    country_short_name3: "NGA",
    country_short_name2: "NG",
    country_phone_code: "234",
  },
  {
    id: 155,
    country_long_name: "Niue",
    country_short_name3: "NIU",
    country_short_name2: "NU",
    country_phone_code: "683",
  },
  {
    id: 156,
    country_long_name: "North Korea",
    country_short_name3: "PRK",
    country_short_name2: "KP",
    country_phone_code: "850",
  },
  {
    id: 157,
    country_long_name: "Northern Mariana Islands",
    country_short_name3: "MNP",
    country_short_name2: "MP",
    country_phone_code: "1-670",
  },
  {
    id: 158,
    country_long_name: "Norway",
    country_short_name3: "NOR",
    country_short_name2: "NO",
    country_phone_code: "47",
  },
  {
    id: 159,
    country_long_name: "Oman",
    country_short_name3: "OMN",
    country_short_name2: "OM",
    country_phone_code: "968",
  },
  {
    id: 160,
    country_long_name: "Pakistan",
    country_short_name3: "PAK",
    country_short_name2: "PK",
    country_phone_code: "92",
  },
  {
    id: 161,
    country_long_name: "Palau",
    country_short_name3: "PLW",
    country_short_name2: "PW",
    country_phone_code: "680",
  },
  {
    id: 162,
    country_long_name: "Palestine",
    country_short_name3: "PSE",
    country_short_name2: "PS",
    country_phone_code: "970",
  },
  {
    id: 163,
    country_long_name: "Panama",
    country_short_name3: "PAN",
    country_short_name2: "PA",
    country_phone_code: "507",
  },
  {
    id: 164,
    country_long_name: "Papua New Guinea",
    country_short_name3: "PNG",
    country_short_name2: "PG",
    country_phone_code: "675",
  },
  {
    id: 165,
    country_long_name: "Paraguay",
    country_short_name3: "PRY",
    country_short_name2: "PY",
    country_phone_code: "595",
  },
  {
    id: 166,
    country_long_name: "Peru",
    country_short_name3: "PER",
    country_short_name2: "PE",
    country_phone_code: "51",
  },
  {
    id: 167,
    country_long_name: "Philippines",
    country_short_name3: "PHL",
    country_short_name2: "PH",
    country_phone_code: "63",
  },
  {
    id: 168,
    country_long_name: "Pitcairn",
    country_short_name3: "PCN",
    country_short_name2: "PN",
    country_phone_code: "64",
  },
  {
    id: 169,
    country_long_name: "Poland",
    country_short_name3: "POL",
    country_short_name2: "PL",
    country_phone_code: "48",
  },
  {
    id: 170,
    country_long_name: "Portugal",
    country_short_name3: "PRT",
    country_short_name2: "PT",
    country_phone_code: "351",
  },
  {
    id: 171,
    country_long_name: "Puerto Rico",
    country_short_name3: " 1-939",
    country_short_name2: "PRI",
    country_phone_code: "1-787",
  },
  {
    id: 172,
    country_long_name: "Qatar",
    country_short_name3: "QAT",
    country_short_name2: "QA",
    country_phone_code: "974",
  },
  {
    id: 173,
    country_long_name: "Republic of the Congo",
    country_short_name3: "COG",
    country_short_name2: "CG",
    country_phone_code: "242",
  },
  {
    id: 174,
    country_long_name: "Reunion",
    country_short_name3: "REU",
    country_short_name2: "RE",
    country_phone_code: "262",
  },
  {
    id: 175,
    country_long_name: "Romania",
    country_short_name3: "ROU",
    country_short_name2: "RO",
    country_phone_code: "40",
  },
  {
    id: 176,
    country_long_name: "Russia",
    country_short_name3: "RUS",
    country_short_name2: "RU",
    country_phone_code: "7",
  },
  {
    id: 177,
    country_long_name: "Rwanda",
    country_short_name3: "RWA",
    country_short_name2: "RW",
    country_phone_code: "250",
  },
  {
    id: 178,
    country_long_name: "Saint Barthelemy",
    country_short_name3: "BLM",
    country_short_name2: "BL",
    country_phone_code: "590",
  },
  {
    id: 179,
    country_long_name: "Saint Helena",
    country_short_name3: "SHN",
    country_short_name2: "SH",
    country_phone_code: "290",
  },
  {
    id: 180,
    country_long_name: "Saint Kitts and Nevis",
    country_short_name3: "KNA",
    country_short_name2: "KN",
    country_phone_code: "1-869",
  },
  {
    id: 181,
    country_long_name: "Saint Lucia",
    country_short_name3: "LCA",
    country_short_name2: "LC",
    country_phone_code: "1-758",
  },
  {
    id: 182,
    country_long_name: "Saint Martin",
    country_short_name3: "MAF",
    country_short_name2: "MF",
    country_phone_code: "590",
  },
  {
    id: 183,
    country_long_name: "Saint Pierre and Miquelon",
    country_short_name3: "SPM",
    country_short_name2: "PM",
    country_phone_code: "508",
  },
  {
    id: 184,
    country_long_name: "Saint Vincent and the Grenadines",
    country_short_name3: "VCT",
    country_short_name2: "VC",
    country_phone_code: "1-784",
  },
  {
    id: 185,
    country_long_name: "Samoa",
    country_short_name3: "WSM",
    country_short_name2: "WS",
    country_phone_code: "685",
  },
  {
    id: 186,
    country_long_name: "San Marino",
    country_short_name3: "SMR",
    country_short_name2: "SM",
    country_phone_code: "378",
  },
  {
    id: 187,
    country_long_name: "Sao Tome and Principe",
    country_short_name3: "STP",
    country_short_name2: "ST",
    country_phone_code: "239",
  },
  {
    id: 188,
    country_long_name: "Saudi Arabia",
    country_short_name3: "SAU",
    country_short_name2: "SA",
    country_phone_code: "966",
  },
  {
    id: 189,
    country_long_name: "Senegal",
    country_short_name3: "SEN",
    country_short_name2: "SN",
    country_phone_code: "221",
  },
  {
    id: 190,
    country_long_name: "Serbia",
    country_short_name3: "SRB",
    country_short_name2: "RS",
    country_phone_code: "381",
  },
  {
    id: 191,
    country_long_name: "Seychelles",
    country_short_name3: "SYC",
    country_short_name2: "SC",
    country_phone_code: "248",
  },
  {
    id: 192,
    country_long_name: "Sierra Leone",
    country_short_name3: "SLE",
    country_short_name2: "SL",
    country_phone_code: "232",
  },
  {
    id: 193,
    country_long_name: "Singapore",
    country_short_name3: "SGP",
    country_short_name2: "SG",
    country_phone_code: "65",
  },
  {
    id: 194,
    country_long_name: "Sint Maarten",
    country_short_name3: "SXM",
    country_short_name2: "SX",
    country_phone_code: "1-721",
  },
  {
    id: 195,
    country_long_name: "Slovakia",
    country_short_name3: "SVK",
    country_short_name2: "SK",
    country_phone_code: "421",
  },
  {
    id: 196,
    country_long_name: "Slovenia",
    country_short_name3: "SVN",
    country_short_name2: "SI",
    country_phone_code: "386",
  },
  {
    id: 197,
    country_long_name: "Solomon Islands",
    country_short_name3: "SLB",
    country_short_name2: "SB",
    country_phone_code: "677",
  },
  {
    id: 198,
    country_long_name: "Somalia",
    country_short_name3: "SOM",
    country_short_name2: "SO",
    country_phone_code: "252",
  },
  {
    id: 199,
    country_long_name: "South Africa",
    country_short_name3: "ZAF",
    country_short_name2: "ZA",
    country_phone_code: "27",
  },
  {
    id: 200,
    country_long_name: "South Korea",
    country_short_name3: "KOR",
    country_short_name2: "KR",
    country_phone_code: "82",
  },
  {
    id: 201,
    country_long_name: "South Sudan",
    country_short_name3: "SSD",
    country_short_name2: "SS",
    country_phone_code: "211",
  },
  {
    id: 202,
    country_long_name: "Spain",
    country_short_name3: "ESP",
    country_short_name2: "ES",
    country_phone_code: "34",
  },
  {
    id: 203,
    country_long_name: "Sri Lanka",
    country_short_name3: "LKA",
    country_short_name2: "LK",
    country_phone_code: "94",
  },
  {
    id: 204,
    country_long_name: "Sudan",
    country_short_name3: "SDN",
    country_short_name2: "SD",
    country_phone_code: "249",
  },
  {
    id: 205,
    country_long_name: "Suriname",
    country_short_name3: "SUR",
    country_short_name2: "SR",
    country_phone_code: "597",
  },
  {
    id: 206,
    country_long_name: "Svalbard and Jan Mayen",
    country_short_name3: "SJM",
    country_short_name2: "SJ",
    country_phone_code: "47",
  },
  {
    id: 207,
    country_long_name: "Swaziland",
    country_short_name3: "SWZ",
    country_short_name2: "SZ",
    country_phone_code: "268",
  },
  {
    id: 208,
    country_long_name: "Sweden",
    country_short_name3: "SWE",
    country_short_name2: "SE",
    country_phone_code: "46",
  },
  {
    id: 209,
    country_long_name: "Switzerland",
    country_short_name3: "CHE",
    country_short_name2: "CH",
    country_phone_code: "41",
  },
  {
    id: 210,
    country_long_name: "Syria",
    country_short_name3: "SYR",
    country_short_name2: "SY",
    country_phone_code: "963",
  },
  {
    id: 211,
    country_long_name: "Taiwan",
    country_short_name3: "TWN",
    country_short_name2: "TW",
    country_phone_code: "886",
  },
  {
    id: 212,
    country_long_name: "Tajikistan",
    country_short_name3: "TJK",
    country_short_name2: "TJ",
    country_phone_code: "992",
  },
  {
    id: 213,
    country_long_name: "Tanzania",
    country_short_name3: "TZA",
    country_short_name2: "TZ",
    country_phone_code: "255",
  },
  {
    id: 214,
    country_long_name: "Thailand",
    country_short_name3: "THA",
    country_short_name2: "TH",
    country_phone_code: "66",
  },
  {
    id: 215,
    country_long_name: "Togo",
    country_short_name3: "TGO",
    country_short_name2: "TG",
    country_phone_code: "228",
  },
  {
    id: 216,
    country_long_name: "Tokelau",
    country_short_name3: "TKL",
    country_short_name2: "TK",
    country_phone_code: "690",
  },
  {
    id: 217,
    country_long_name: "Tonga",
    country_short_name3: "TON",
    country_short_name2: "TO",
    country_phone_code: "676",
  },
  {
    id: 218,
    country_long_name: "Trinidad and Tobago",
    country_short_name3: "TTO",
    country_short_name2: "TT",
    country_phone_code: "1-868",
  },
  {
    id: 219,
    country_long_name: "Tunisia",
    country_short_name3: "TUN",
    country_short_name2: "TN",
    country_phone_code: "216",
  },
  {
    id: 220,
    country_long_name: "Turkey",
    country_short_name3: "TUR",
    country_short_name2: "TR",
    country_phone_code: "90",
  },
  {
    id: 221,
    country_long_name: "Turkmenistan",
    country_short_name3: "TKM",
    country_short_name2: "TM",
    country_phone_code: "993",
  },
  {
    id: 222,
    country_long_name: "Turks and Caicos Islands",
    country_short_name3: "TCA",
    country_short_name2: "TC",
    country_phone_code: "1-649",
  },
  {
    id: 223,
    country_long_name: "Tuvalu",
    country_short_name3: "TUV",
    country_short_name2: "TV",
    country_phone_code: "688",
  },
  {
    id: 224,
    country_long_name: "U.S. Virgin Islands",
    country_short_name3: "VIR",
    country_short_name2: "VI",
    country_phone_code: "1-340",
  },
  {
    id: 225,
    country_long_name: "Uganda",
    country_short_name3: "UGA",
    country_short_name2: "UG",
    country_phone_code: "256",
  },
  {
    id: 226,
    country_long_name: "Ukraine",
    country_short_name3: "UKR",
    country_short_name2: "UA",
    country_phone_code: "380",
  },
  {
    id: 227,
    country_long_name: "United Arab Emirates",
    country_short_name3: "ARE",
    country_short_name2: "AE",
    country_phone_code: "971",
  },
  {
    id: 228,
    country_long_name: "United Kingdom",
    country_short_name3: "GBR",
    country_short_name2: "GB",
    country_phone_code: "44",
  },
  {
    id: 229,
    country_long_name: "United States",
    country_short_name3: "USA",
    country_short_name2: "US",
    country_phone_code: "1",
  },
  {
    id: 230,
    country_long_name: "Uruguay",
    country_short_name3: "URY",
    country_short_name2: "UY",
    country_phone_code: "598",
  },
  {
    id: 231,
    country_long_name: "Uzbekistan",
    country_short_name3: "UZB",
    country_short_name2: "UZ",
    country_phone_code: "998",
  },
  {
    id: 232,
    country_long_name: "Vanuatu",
    country_short_name3: "VUT",
    country_short_name2: "VU",
    country_phone_code: "678",
  },
  {
    id: 233,
    country_long_name: "Vatican",
    country_short_name3: "VAT",
    country_short_name2: "VA",
    country_phone_code: "379",
  },
  {
    id: 234,
    country_long_name: "Venezuela",
    country_short_name3: "VEN",
    country_short_name2: "VE",
    country_phone_code: "58",
  },
  {
    id: 235,
    country_long_name: "Vietnam",
    country_short_name3: "VNM",
    country_short_name2: "VN",
    country_phone_code: "84",
  },
  {
    id: 236,
    country_long_name: "Wallis and Futuna",
    country_short_name3: "WLF",
    country_short_name2: "WF",
    country_phone_code: "681",
  },
  {
    id: 237,
    country_long_name: "Western Sahara",
    country_short_name3: "ESH",
    country_short_name2: "EH",
    country_phone_code: "212",
  },
  {
    id: 238,
    country_long_name: "Yemen",
    country_short_name3: "YEM",
    country_short_name2: "YE",
    country_phone_code: "967",
  },
  {
    id: 239,
    country_long_name: "Zambia",
    country_short_name3: "ZMB",
    country_short_name2: "ZM",
    country_phone_code: "260",
  },
  {
    id: 240,
    country_long_name: "Zimbabwe",
    country_short_name3: "ZWE",
    country_short_name2: "ZW",
    country_phone_code: "263",
  },
];
